version: "3.8"
services:
  apiserver:
    container_name: apiserver
    image: allegroai/clearml:2.0.0
    command: apiserver
    depends_on:
      - mongo
      - redis
      - elasticsearch
    ports:
      - "8008:8008"
    environment:
      CLEARML_ELASTIC_SERVICE_HOST: elasticsearch
      CLEARML_ELASTIC_SERVICE_PORT: 9200
      CLEARML_REDIS_SERVICE_HOST: redis
      CLEARML_REDIS_SERVICE_PORT: 6379
      CLEARML_MONGODB_SERVICE_HOST: mongo
      CLEARML_MONGODB_SERVICE_PORT: 27017

  webserver:
    container_name: webserver
    image: allegroai/clearml:2.0.0
    command: webserver
    depends_on:
      - apiserver
    environment:
      CLEARML_LOG_LEVEL: DEBUG
      CLEARML_WEB_HOST: 
    ports:
      - "8080:80"

  fileserver:
    container_name: fileserver
    image: allegroai/clearml:2.0.0
    command: fileserver
    ports:
      - "8081:8081"

  mongo:
    image: mongo:5
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6
    container_name: redis
    restart: always

  elasticsearch:
    image: elasticsearch:9.1.7
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioaccess
      MINIO_ROOT_PASSWORD: miniosecret
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
  
  ml_service:
    build: ../service
    container_name: ml_service
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - minio
      - apiserver
      - webserver
      - fileserver

  dashboard:
    build: ../dashboard
    container_name: dashboard
    ports:
      - "8501:8501"
    depends_on:
      - ml_service

volumes:
  minio_data:
  mongo_data:
  elastic_data:
