apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - name: grpc
        image: grpc-client:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-client
spec:
  type: NodePort
  selector:
    app: grpc-client
  ports:
    - port: 50051
      targetPort: 50051
      nodePort: 30003
